### ISSUE TITLE
Price information on Product Pages is not dynamically updated when locale changes.

### ISSUE THREAD

**Issue by egant** [rylanharper/Nitrogen#10]
Hi,

The Collection Pages will update the displayed product price information if I change the locale. Is it possible to have the product pages do this too?

**Comment by rylanharper** [comment]
Hey @egant!

I'm having trouble replicating this on my end. Localized prices work correctly on both collection and product pages for me (on local and live). Do you have any more information or a workflow you go through to replicate this issue?

**Comment by egant** [comment]
hey @rylanharper !

In this store's Tax settings, I am collecting taxes at different rates when selling to different countries in the EU. I can see the behavior difference with the product page by opening  [test instance](https://5581dc68.nitroshop.pages.dev/collections/latest) in an incognito window.

There, I see the prices for default country (FR) on the three products displayed, I then change Country from FR to DE and save and I will see prices decrease slightly, next I can change country to Italy and save and see prices increase.

If I load one of those product pages and change country and save there is no update to price after saving the new country, but if I then refresh the product page I will see the updated price.

**Comment by rylanharper** [comment]
@egant I just pushed changes to the `ProductForm` component (along with minor updates to other pages/components) in 8f35b560da62310525662280e8ab258c16b4e979. Can you see if these fixed the issue? Seems to be fixed on my end with single-variant products.

**Comment by egant** [comment]
@rylanharper yes, that fixes the issue. thank you for jumping on it so quickly.

**Comment by rylanharper** [comment]
Sorry, forgot to add that this was a quick fix that I did today, but I may refactor this into something else later on this week if I find a better solution. This is a stable fix though!
