### ISSUE TITLE
Amazing project!

### ISSUE THREAD

**Issue by Baroshem** [rylanharper/Nitrogen#2]
Hey Buddy!

This is an amazing project you have built there! I was working on something similar some time ago.

Maybe we could join forces?

I would be very happy to contribute and help you in any way possible (also from the advocacy side like writing articles and giving conference talks about it).

Could you add me on Discord so that we could talk about it? :)

My username is jakubandrzejewski

**Comment by rylanharper** [comment]
Hey @Baroshem 

Big fan of your work! Yes, I would absolutely love some help on this repo! And any advocacy to highlight this would be phenomenal.

I have a lot planned for it (although don't want to add to much at once), and it would be great to go over some basic things that I can use some help/guidance on. I'm really trying to have this be the main starting point for Nuxt devs working with Shopify in a headless environment. A couple of things I have planned:
- Reccomended products component - *current wip*
- Product descriptions (multiple, with metafields) - *current wip*
- Collection products pagination (not sure if I should have a "load more" or numbered page select)
- Revamped product-cards (with swatch color selection and quick add-to-cart)
- Wishlist functionality (add a new wishlist Pinia store)
- Reviews component (using Yotpo)
- Sanity integration
- Klaviyo integration

A couple things I might refactor:
- Possibly change the product options to be more classic (not involving metafields). Although the current approach is more modern and a lot more easily managed on the admin side of things
- A site redesign, possibly with NuxtUI 3

I'll message you on Discord later today!

**Comment by jupelost** [comment]
Any plans on adding Shopify analytics? Or is that not even possible as of right now

**Comment by rylanharper** [comment]
@jupelost That would be cool, what analytics do you have in mind? I have some queries add in the GraphQL that keep track of basic analytics such as `trackingParameters` when using search or predictiveSearch (for instance, https://shopify.dev/docs/api/storefront/2024-10/objects/Product#field-trackingparameters)

This is honestly an area where I don't have much experience, but would like to improve in. If you have anything in mind, let me know and I can try to integrate this :)

**Comment by jupelost** [comment]
The official analytics, I know that Hydrogen has an Analytics Component that they wrap their entire app with and it sends a payload with page view and cart view cookies or something like that im not too well versed on the topic. Maybe there's a way to implement that similarly in Nuxt? I remember reading an article by [Karve Digital](https://karvedigital.com/insights/integrating-shopify-analytics-into-your-next-js-custom-storefront) doing something similar but in Next JS using the hydrogen-react library that Shopify made.

**Comment by rylanharper** [comment]
@jupelost I'll look into integrating this. Definitely feel analytics should be included in this repo. I'm trying to wrap up the last of the core Shopify-based components next week and then I'll check this out.

**Comment by rylanharper** [comment]
Closing this issue. Will reopen another issue with a more detailed one for the Shopify analytics towards the end of the week with a "help wanted" label. In the meantime, I'll do some research on this.
